### PR TITLE
Refactor to objects. Fix duplicate detection.

### PR DESCRIPTION
**Pull request by davidmorgan**
This change is [Reviewable](https://reviewable.io/reviews/google/enum_class.dart/24)

### CODE REVIEW

**Comment by manuelF** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

_[enum_class_generator/pubspec.yaml, line 17 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9SNemcXeG8tzAynRg:-KM9SNemcXeG8tzAynRh:-1371543506) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/pubspec.yaml#L17)):_

> ``` YAML
>   built_collection: '^1.0.0'
>   built_value: '^0.1.1'
> #  enum_class: '^1.0.0'
> ```

Why a comment here? 

---

_[enum_class_generator/lib/src/source_class.dart, line 61 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9h0AMp6UyynMl2Xhq:-KM9h0AMp6UyynMl2Xhr:-524219242) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_class.dart#L61)):_

> ``` Dart
>     final matches = new RegExp(r'static BuiltSet<' +
>             classElement.displayName +
>             r'> get values => (_\$\w+)\;')
> ```

What could happen with whitespace in this regexp if displayName is very long? Isn't \s+ better for this case? Or does toSource guarantee it is not a problem?

---

_[enum_class_generator/lib/src/source_library.dart, line 83 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9gOjaJnhht__8ugYS:-KM9gOjbdksaT66Y52fK:523403308) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_library.dart#L83)):_

> ``` Dart
>           result.add(
>               'Generated identifier "$identifier" is used multiple times in'
>               ' $name, change to something else.');
> ```

Change what to something else?

---

_[enum_class_generator/tool/build.dart, line 1 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9fza8pXqVZNrzEK-8:-KM9fza9WQr3X79FIg3m:1644635439) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/tool/build.dart#L1)):_

> ``` Dart
> // Copyright (c) 2015, Google Inc. Please see the AUTHORS file for details.
> ```

s/2015/2016

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/google/enum_class.dart/24)_

**Comment by davidmorgan** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

_[enum_class_generator/pubspec.yaml, line 17 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9SNemcXeG8tzAynRg:-KMNqDXyFXRXLgWJlLdK:1172436885) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/pubspec.yaml#L17)):_
<details><summary>

<i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary>



> Why a comment here? 
> </details>
> The commented value is what I'll actually submit; the one with "path" is for the benfit of this review, so the tests can run.

With updated versions the tests will only run if I publish the packages. Haven't quite figured out the best way to manage this yet, but, this is one option :)

---

_[enum_class_generator/lib/src/source_class.dart, line 61 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9h0AMp6UyynMl2Xhq:-KMNqfFcng7QWSDy971d:-104184663) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_class.dart#L61)):_
<details><summary>

<i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary>



> What could happen with whitespace in this regexp if displayName is very long? Isn't \s+ better for this case? Or does toSource guarantee it is not a problem?
> </details>
> Yes, toSource means it's not a problem; we're going via the AST and there is no extra formatting/whitespace introduced.

It _is_ possible to get the original source via the analyzer, in which case this would be a problem.

---

_[enum_class_generator/lib/src/source_library.dart, line 83 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9gOjaJnhht__8ugYS:-KMNr7Hq8JdAL4HmtmmV:205167769) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_library.dart#L83)):_
<details><summary>

<i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary>



> Change what to something else?
> </details>
> The identifier. So if you wrote

static const MyEnum ENABLED = _$ENABLED;

the message would read

Generated identifier "_$ENABLED" is used multiple times in my_enum_library, change to something else.

And you need to rename one use of _$ENABLED.

---

_[enum_class_generator/tool/build.dart, line 1 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9fza8pXqVZNrzEK-8:-KMNrtmAKD8Jewr34m78:-499146009) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/tool/build.dart#L1)):_
<details><summary>

<i>Previously, manuelF (Manuel Ferreria) wrote…</i></summary>



> s/2015/2016
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/google/enum_class.dart/24)_

**Comment by manuelF** [comment]
:lgtm:

---

Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/google/enum_class.dart/24#-:-KMO1koHhkZWwJ0PJol5:1417088721)_

**Comment by BlackHC** [comment]
Reviewed 12 of 15 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[enum_class_generator/lib/src/source_class.dart, line 61 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9h0AMp6UyynMl2Xhq:-KMOj3oS4iVQ5Qly2dFa:-1460021186) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_class.dart#L61)):_
<details><summary>

<i>Previously, davidmorgan (David Morgan) wrote…</i></summary>



> Yes, toSource means it's not a problem; we're going via the AST and there is no extra formatting/whitespace introduced.
> 
> It _is_ possible to get the original source via the analyzer, in which case this would be a problem.
> </details>
> You could reparse the matches to ensure that they are a list literal. Also why do you specify this is a getter? A static const List would be more optimal as it will only be created once on demand instead of being recreated on every access :)

---

_[enum_class_generator/lib/src/source_class.dart, line 67 [r3]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KMOkyaJ9EKfSrwoNG9n:-KMOkyaKovy9cxCLavS8:-817991221) ([raw file](https://github.com/google/enum_class.dart/blob/3e5e4946d3a258f21329833407257cc50d5035b7/enum_class_generator/lib/src/source_class.dart#L67)):_

> ``` Dart
> 
>   static bool isMissingImportFor(ClassElement classElement) {
>     return classElement.supertype.displayName != 'EnumClass' &&
> ```

Is there a more direct way to test for it?

---

_[enum_class_generator/lib/src/source_field.dart, line 62 [r3]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KMOnOcBWRlZhREhNekL:-KMOnOcCeWETCiumbtgu:-1769546285) ([raw file](https://github.com/google/enum_class.dart/blob/3e5e4946d3a258f21329833407257cc50d5035b7/enum_class_generator/lib/src/source_field.dart#L62)):_

> ``` Dart
>       result.add('Make field "$name" const.');
>     } else if (!generatedIdentifier.startsWith('_\$')) {
>       result.add('Initialize field "$name" with a value starting "_\$".');
> ```

I feel this error message could use more explanations (ie don't reuse names, maybe just use the field name prefixed with _ etc to make it clearer what this is about?

---

_[enum_class_generator/lib/src/source_library.dart, line 83 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9gOjaJnhht__8ugYS:-KMPUY2owMmrtfoLm0-r:784266146) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_library.dart#L83)):_
<details><summary>

<i>Previously, davidmorgan (David Morgan) wrote…</i></summary>



> The identifier. So if you wrote
> 
> static const MyEnum ENABLED = _$ENABLED;
> 
> the message would read
> 
> Generated identifier "_$ENABLED" is used multiple times in my_enum_library, change to something else.
> 
> And you need to rename one use of _$ENABLED.
> </details>
> I agree with Manuel. The explanation could be more explicit. Why do we even give the clients freedom to pick this name?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/google/enum_class.dart/24)_

**Comment by davidmorgan** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[enum_class_generator/lib/src/source_class.dart, line 61 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9h0AMp6UyynMl2Xhq:-KMPWp19kgg3iOnb1hYk:760427210) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_class.dart#L61)):_
<details><summary>

<i>Previously, BlackHC (Andreas Kirsch) wrote…</i></summary>



> You could reparse the matches to ensure that they are a list literal. Also why do you specify this is a getter? A static const List would be more optimal as it will only be created once on demand instead of being recreated on every access :)
> </details>
> Hmm, I think you misunderstand, this is parsing a line like so:

static BuiltSet<Foo> get values => _$values;

In the generated code we implement it as a field.

---

_[enum_class_generator/lib/src/source_class.dart, line 67 [r3]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KMOkyaJ9EKfSrwoNG9n:-KMPX4B6RHjBPeVm4JCZ:48864274) ([raw file](https://github.com/google/enum_class.dart/blob/3e5e4946d3a258f21329833407257cc50d5035b7/enum_class_generator/lib/src/source_class.dart#L67)):_
<details><summary>

<i>Previously, BlackHC (Andreas Kirsch) wrote…</i></summary>



> Is there a more direct way to test for it?
> </details>
> To test if the import is missing?

The problem is, if the import is missing, the supertype is omitted from the parsed AST. i.e. if you write "extends NotImportedClass" then it's just dropped. So we go back to the source to see if that's what you were trying to do...

I'm not actually sure this check is worth it, we might drop it. The problem is that extending EnumClass is the trigger for the generator, so you extend EnumClass but forget to import it you may get confused. _shrug_ 

---

_[enum_class_generator/lib/src/source_field.dart, line 62 [r3]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KMOnOcBWRlZhREhNekL:-KMPYm7dn-CAyJQBKxpm:-1605305189) ([raw file](https://github.com/google/enum_class.dart/blob/3e5e4946d3a258f21329833407257cc50d5035b7/enum_class_generator/lib/src/source_field.dart#L62)):_
<details><summary>

<i>Previously, BlackHC (Andreas Kirsch) wrote…</i></summary>



> I feel this error message could use more explanations (ie don't reuse names, maybe just use the field name prefixed with _ etc to make it clearer what this is about?
> </details>
> Eh. I would expect people to look at an example, at which point this is pretty clear.

If they're just getting started, they're likely to get a whole pile of errors; the best path is really to look at an example.

Actually -- what about if we include the URL to the example in the error message?

---

_[enum_class_generator/lib/src/source_library.dart, line 83 [r1]](https://reviewable.io:443/reviews/google/enum_class.dart/24#-KM9gOjaJnhht__8ugYS:-KMPXedn7EJJfSVxqWgt:217665118) ([raw file](https://github.com/google/enum_class.dart/blob/84da2b40a0f6333e5206796dba4f317653cdd220/enum_class_generator/lib/src/source_library.dart#L83)):_
<details><summary>

<i>Previously, BlackHC (Andreas Kirsch) wrote…</i></summary>



> I agree with Manuel. The explanation could be more explicit. Why do we even give the clients freedom to pick this name?
> </details>
> Since the name can be anything at all we let users pick it for two reasons, 1) they might want to choose something shorter:

static const MyEnum reallyLongValueOne = $_rlvo;
static const MyEnum reallyLongValueTwo = $_rlvt;
static const MyEnum reallyLongValueThree = $_rlvth;

but more importantly 2) they might clash:

class MyEnum {
  static const MyEnum enabled = $_enabled;
  ...
}

class MyOtherEnum {
  static const MyEnum2 enabled = $_enabled;
  ...
}

If these are in the same library then they clash and the user needs to pick a different name.

We could namespace the generated constants, but that makes the whole thing longer again:

class MyEnum {
  static const MyEnum enabled = $_MyEnum.enabled;
 }

and requires an unnecessary class definition.

It's all a bit awkward, but I think the current solution is a nice compromise.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/google/enum_class.dart/24)_

**Pull request merged**
